module Operations where

import Operations.Add
import Operations.Addi
import Operations.And
import Operations.Branch
import Operations.Call
import Operations.Callpar
import Operations.CmpJmp
import Operations.Decr
import Operations.Incr
import Operations.Li
import Operations.Lw
import Operations.Lwi
import Operations.Move
import Operations.Mul
import Operations.Not
import Operations.Or
import Operations.ResetParams
import Operations.Return
import Operations.SetParams
import Operations.Sub
import Operations.Subi
import Operations.Sw
import Operations.Swi
import Operations.Wait
import Operations.Xor

operations = listArray (0,63) [add
                             , addi
                             , and
                             , branch
                             , call
                             , callpar
                             , cmpJmp
                             , decr
                             , incr
                             , li
                             , lw
                             , lwi
                             , move
                             , mul
                             , not'
                             , or
                             , resetParams
                             , return'
                             , setParams
                             , sub
                             , subi
                             , sw
                             , swi
                             , wait
                             , xor']
